name: Test Packages

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        env:
          SKIP_YARN_COREPACK_CHECK: true
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - run: yarn install

      - name: Test OpenAI Package
        working-directory: ./packages/openai
        run: yarn test
